### ISSUE TITLE
compling Error after upgrading Okta Signin Widget from 6.1.0 to 6.3.0

### ISSUE THREAD

**Issue by udayshetty** [okta/okta-signin-widget#2505]
### Describe the bug

Angular 12 ,updated @okta/okta-signin-widget from 6.1.0  to  6.3.0.  getting bunch of errors during compliation

### What is expected to happen?

complie without  errors

### What is the actual behavior?

Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/CourageForSigninWidget.d.ts:7:22 - error TS2307: Cannot find module 'backbone' or its corresponding type declarations.
7 import Backbone from 'backbone';
                      ~~~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/framework/Collection.d.ts:1:23 - error TS2688: Cannot find type definition file for 'jquery'.

1 /// <reference types="jquery" />
                        ~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/framework/Collection.d.ts:2:35 - error TS2307: Cannot find module 'backbone' or its corresponding type declarations.

2 import Backbone, { _Result } from 'backbone';
                                    ~~~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/framework/Collection.d.ts:14:18 - error TS2304: Cannot find name 'JQueryXHR'.

14     fetchMore(): JQueryXHR;
                    ~~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/framework/Model.d.ts:1:22 - error TS2307: Cannot find module 'backbone' or its corresponding type declarations.

1 import Backbone from 'backbone';
                     ~~~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/framework/View.d.ts:1:23 - error TS2688: Cannot find type definition file for 'jquery'.

1 /// <reference types="jquery" />
                        ~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/framework/View.d.ts:2:23 - error TS2688: Cannot find type definition file for 'jqueryui'.

2 /// <reference types="jqueryui" />
                        ~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/framework/View.d.ts:3:23 - error TS2688: Cannot find type definition file for 'selectize'.

3 /// <reference types="selectize" />
                        ~~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/framework/View.d.ts:4:35 - error TS2307: Cannot find module 'backbone' or its corresponding type declarations.

4 import Backbone, { _Result } from 'backbone';
                                    ~~~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/framework/View.d.ts:25:39 - error TS2304: Cannot find name 'JQuery'.

25     setElement(element: HTMLElement | JQuery): this;
                                         ~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/framework/View.d.ts:31:10 - error TS2304: Cannot find name 'JQuery'.

31     $el: JQuery;
            ~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/framework/View.d.ts:33:26 - error TS2304: Cannot find name 'JQuery'.

33     $(selector: string): JQuery;
                            ~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/models/BaseCollection.d.ts:2:25 - error TS2307: Cannot find module 'backbone' or its corresponding type declarations.

2 import { _Result } from 'backbone';
                          ~~~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/models/Model.d.ts:2:25 - error TS2307: Cannot find module 'backbone' or its corresponding type declarations.

2 import { _Result } from 'backbone';
                          ~~~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/util/BaseController.d.ts:1:23 - error TS2688: Cannot find type definition file for 'backbone'.

1 /// <reference types="backbone" />
                        ~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/util/BaseController.d.ts:14:11 - error TS2503: Cannot find namespace 'Backbone'.

14     root: Backbone._Result<string>;
             ~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/util/BaseRouter.d.ts:1:23 - error TS2688: Cannot find type definition file for 'jquery'.

1 /// <reference types="jquery" />
                        ~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/util/BaseRouter.d.ts:2:22 - error TS2307: Cannot find module 'backbone' or its corresponding type declarations.

2 import Backbone from 'backbone';
                       ~~~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/util/BaseRouter.d.ts:34:33 - error TS2503: Cannot find namespace 'JQuery'.

34     el?: HTMLElement | string | JQuery.PlainObject;
                                   ~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/util/BaseRouter.d.ts:37:49 - error TS2503: Cannot find namespace 'JQuery'.

37     el: Backbone._Result<string | HTMLElement | JQuery.PlainObject>;
                                                   ~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/util/jquery-wrapper.d.ts:1:23 - error TS2688: Cannot find type definition file for 'jquery'.

1 /// <reference types="jquery" />
                        ~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/util/jquery-wrapper.d.ts:2:23 - error TS2688: Cannot find type definition file for 'jqueryui'.

2 /// <reference types="jqueryui" />
                        ~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/util/jquery-wrapper.d.ts:3:23m - error TS2688: Cannot find type definition file for 'selectize'.

3 /// <reference types="selectize" />
                        ~~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/util/jquery-wrapper.d.ts:4:37 - error TS2304: Cannot find name 'JQuery'.

4 export interface OktaJQuery extends JQuery<HTMLElement> {
                                      ~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/util/jquery-wrapper.d.ts:5:44 - error TS2304: Cannot find name 'JQuery'.

5     scrollParent(includeHidden?: boolean): JQuery<HTMLElement>;
                                             ~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/util/jquery-wrapper.d.ts:17:43 - error TS2304: Cannot find name 'JQueryStatic'.

17 export interface OktaJQueryStatic extends JQueryStatic {
                                             ~~~~~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/util/jquery-wrapper.d.ts:18:16 - error TS2503: Cannot find namespace 'JQuery'.

18     (selector: JQuery.Selector, context?: Element | Document | JQuery | JQuery.Selector): OktaJQuery;
                  ~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/util/jquery-wrapper.d.ts:18:64 - error TS2304: Cannot find name 'JQuery'.

18     (selector: JQuery.Selector, context?: Element | Document | JQuery | JQuery.Selector): OktaJQuery;
                                                                  ~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/util/jquery-wrapper.d.ts:18:73 - error TS2503: Cannot find namespace 'JQuery'.

18     (selector: JQuery.Selector, context?: Element | Document | JQuery | JQuery.Selector): OktaJQuery;
                                                                           ~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/courage/util/underscore-wrapper.d.ts:1:15 - error TS7016: Could not find a declaration file for module 'underscore'. 'C:/TFS/VS2015/Applications/ECROnline/Dev/ECROnline/WebApp/node_modules/underscore/underscore-umd.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/underscore` if it exists or add a new declaration (.d.ts) file containing `declare module 'underscore';`

1 import _ from 'underscore';
                ~~~~~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/src/models/Settings.d.ts:1:23 - error TS2688: Cannot find type definition file for 'backbone'.

1 /// <reference types="backbone" />
                        ~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/src/models/Settings.d.ts:14:15 - error TS7016: Could not find a declaration file for module 'q'. 'C:/TFS/VS2015/Applications/ECROnline/Dev/ECROnline/WebApp/node_modules/q/q.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/q` if it exists or add a new declaration (.d.ts) file containing `declare module 'q';`
14m import Q from 'q';
                 ~~~
Error: node_modules/@okta/okta-signin-widget/types/src/models/Settings.d.ts:21:19 - error TS2503: Cannot find namespace 'Backbone'.
21     get<A extends Backbone._StringKey<SettingsProps>>(attributeName: A): any;
                     ~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/src/views/shared/Header.d.ts:12:23 - error TS2688: Cannot find type definition file for 'jquery'.

12 /// <reference types="jquery" />
                         ~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/src/views/shared/Header.d.ts:13:23 - error TS2688: Cannot find type definition file for 'jqueryui'.

13 /// <reference types="jqueryui" />
                         ~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/src/views/shared/Header.d.ts:14:23 - error TS2688: Cannot find type definition file for 'selectize'.

14 /// <reference types="selectize" />
                         ~~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/src/views/shared/Header.d.ts:24:21 - error TS2304: Cannot find name 'JQuery'.

24     getContentEl(): JQuery<HTMLElement>;
                       ~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/src/v2/BaseLoginRouter.d.ts:12:23 - error TS2688: Cannot find type definition file for 'backbone'.

12 /// <reference types="backbone" />
                         ~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/src/v2/BaseLoginRouter.d.ts:19:20 - error TS2305: Module '"@okta/okta-auth-js"' has no exported member 'IdxResponse'.

19 import { OktaAuth, IdxResponse } from '@okta/okta-auth-js';
                      ~~~~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/src/v2/BaseLoginRouter.d.ts:46:95 - error TS2694: Namespace '"C:/TFS/VS2015/Applications/ECROnline/Dev/ECROnline/WebApp/node_modules/@okta/okta-auth-js/lib/index"' has no exported member 'IdxRemediation'.

46     hasAuthenticationSucceeded(idxResponse: IdxResponse): true | import("@okta/okta-auth-js").IdxRemediation;
                                                                                                 ~~~~~~~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/src/v2/client/formatError.d.ts:12:10 - error TS2305: Module '"@okta/okta-auth-js"' has no exported member 'IdxResponse'.

12 import { IdxResponse } from '@okta/okta-auth-js';
            ~~~~~~~~~~~
Error: node_modules/@okta/okta-signin-widget/types/src/v2/models/AppState.d.ts:12:23 - error TS2688: Cannot find type definition file for 'backbone'.

12 /// <reference types="backbone" />
                         ~~~~~~~~

Error: node_modules/@okta/okta-signin-widget/types/src/v2/models/AppState.d.ts:21:19 - error TS2503: Cannot find namespace 'Backbone'.

21     get<A extends Backbone._StringKey<AppStateProps>>(attributeName: A): any;
                     ~~~~~~~~



### Reproduction Steps

ng serve

### SDK Versions

[package.zip](https://github.com/okta/okta-signin-widget/files/8643344/package.zip)


### Execution Environment

Windows 10 ,  npm 7.5.6 , node 16.15.0, Angular 12.1.1


### Additional Information?

It also fails with same set of error when you upgrade okta/okta-signin-widget from 6.1.0  to 6.2.0

**Comment by aarongranick-okta** [comment]
@udayshetty You should be able to upgrade to widget 6.2.x without seeing any Typescript errors, as types were only added to the widget in version 6.3.0: https://github.com/okta/okta-signin-widget/commit/bd9162967304aa12398cdd759b1760f99b095f04

**Comment by aarongranick-okta** [comment]
@udayshetty I have created a draft PR with fix here: https://github.com/okta/okta-signin-widget/pull/2509

I have tested using this sample: https://github.com/okta/samples-js-angular/tree/master/custom-login

I had to make add these 2 lines in `tsconfig.json`:

```
  "angularCompilerOptions": {
    "esModuleInterop": true,
    "allowSyntheticDefaultExports": true
  }
  ```
  
  Because the Backbone library uses `export = ` syntax in its type declarations.
  
  I also set the version of `@okta/okta-auth-js` to `6.4.5` (it should match what is used in the widget)
  
  If you are able to confirm that this draft PR will fix your issue we can get the fix published quicker. 
  
  Thanks for bringing this issue to our attention!

**Comment by udayshetty** [comment]
> @udayshetty You should be able to upgrade to widget 6.2.x without seeing any Typescript errors, as types were only added to the widget in version 6.3.0: [bd91629](https://github.com/okta/okta-signin-widget/commit/bd9162967304aa12398cdd759b1760f99b095f04)
