### ISSUE TITLE
test cases are failing

### ISSUE THREAD

**Issue by patil-akshay** [okta/okta-signin-widget#1170]
I am submitting a bug report.

### I'm submitting a
  - [ 1 ] bug report
  - [ ] feature request

### Background info

After upgrading from osw 3.9.2 to 4.0.0 most of the test cases are failing.

Relevant file
```test/unit/spec/EnrollQuestions_spec.js```

Error msg:
```HeadlessChrome 81.0.4044 (Mac OS X 10.14.6) EnrollDuo displays the correct factorBeacon FAILED
	TypeError: this.controller.fetchInitialData(...).then(...).fail is not a function
	    at <Jasmine>
	    at child.render (webpack:///src/util/BaseLoginRouter.js:272:10 <- test/unit/main.js:69626:17)
	    at child.enrollDuo (webpack:///src/LoginRouter.js:299:12 <- test/unit/main.js:14868:12)
	    at webpack:///test/unit/spec/EnrollDuo_spec.js:53:20 <- test/unit/main.js:77569:18
	    at _fulfilled (webpack:///node_modules/q/q.js:834:1 <- test/unit/main.js:12336:54)
	    at webpack:///node_modules/q/q.js:863:1 <- test/unit/main.js:12365:30
	    at Promise.promise.promiseDispatch (webpack:///node_modules/q/q.js:796:1 <- test/unit/main.js:12298:13)
	    at webpack:///node_modules/q/q.js:604:1 <- test/unit/main.js:12106:44
	    at runSingle (webpack:///node_modules/q/q.js:137:1 <- test/unit/main.js:11639:13)
	    at flush (webpack:///node_modules/q/q.js:125:1 <- test/unit/main.js:11627:13)
	    at module.exports (node_modules/babel-polyfill/dist/polyfill.js:993:25)```


### Your environment

  - Okta Sign-In Widget Version: 4.0.0
  - OS: mac

**Comment by patil-akshay** [comment]
.
