### ISSUE TITLE
Sign-In Widget 6.5 doesn't compile in Angular 14 app

### ISSUE THREAD

**Issue by mraible** [okta/okta-signin-widget#2573]
### Describe the bug

I’m experiencing issues when trying to use the latest Sign-In Widget in an Angular 14 app.

```
Error: node_modules/@okta/okta-signin-widget/types/src/models/Hooks.d.ts:12:23 - error TS2307: Cannot find module 'okta' or its corresponding type declarations.

12 import { Model } from 'okta';
```

More information is in https://github.com/okta-samples/okta-angular-sample/pull/503.

### What is expected to happen?

It should compile without errors. It works fine in 6.3.5. https://github.com/okta-samples/okta-angular-sample/pull/495

### What is the actual behavior?

Compile errors

### Reproduction Steps

See PR above

### SDK Versions

Latest and greatest 

### Execution Environment

Node 16

**Comment by jaredperreault-okta** [comment]
Thanks for finding this work around @TommyPang! We will look into this

Internal Ref: OKTA-504464

**Comment by udayshetty** [comment]
Getting same error when upgrading from 6.2.0 to 6.4.3 in Angular 12 , applied  temp workaround suggested by TommyPang , but seeing warnings during compliation.

Warning: .....\node_modules\@okta\okta-auth-js\esm\esm.browser.js depends 
on '@babel/runtime-corejs3/regenerator'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: .....\node_modules\clipboard\lib\clipboard.js depends on 'good-listener'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

packages.json: "@okta/okta-angular": "^5.2.0",
    "@okta/okta-auth-js": "^6.1.0",
    "@okta/okta-signin-widget": "^6.4.3",

**Comment by denysoblohin-okta** [comment]
As a workaround, you can add `paths` in `compilerOptions` of `tsconfig.json`
```js
    "paths": {
      "okta": ["./node_modules/@okta/okta-signin-widget/types/packages/@okta/courage-dist/types/index.d.ts"],
    }
```

Also enable `allowSyntheticDefaultImports`.

To bypass warnings about CommonJs please add to `build.options` in `angular.json`:
```js
            "allowedCommonJsDependencies": [
              "detect-node",
              "@babel/runtime-corejs3/regenerator",
              "q",
              "parse-ms",
              "@sindresorhus/to-milliseconds",
              "clipboard",
              "cross-fetch",
              "tiny-emitter",
              "p-cancelable"
            ],
```

**Comment by fseee** [comment]
Have same error, just in case below is a working combo of auth-js and signin-widget:

```
"@okta/okta-auth-js": "6.4.5",
"@okta/okta-signin-widget": "6.3.3"
```

**Comment by chiranjiv95** [comment]
> ### Describe the bug
> I’m experiencing issues when trying to use the latest Sign-In Widget in an Angular 14 app.
> 
> ```
> Error: node_modules/@okta/okta-signin-widget/types/src/models/Hooks.d.ts:12:23 - error TS2307: Cannot find module 'okta' or its corresponding type declarations.
> 
> 12 import { Model } from 'okta';
> ```
> 
> More information is in [okta-samples/okta-angular-sample#503](https://github.com/okta-samples/okta-angular-sample/pull/503).
> 
> ### What is expected to happen?
> It should compile without errors. It works fine in 6.3.5. [okta-samples/okta-angular-sample#495](https://github.com/okta-samples/okta-angular-sample/pull/495)
> 
> ### What is the actual behavior?
> Compile errors
> 
> ### Reproduction Steps
> See PR above
> 
> ### SDK Versions
> Latest and greatest
> 
> ### Execution Environment
> Node 16
> 
> ### Additional Information?
> _No response_

has the issue been resolved? I'm facing the same prblm.

**Comment by denysoblohin-okta** [comment]
Fix for this issue will be available in next widget release

**Comment by mraible** [comment]
@denysoblohin-okta Do you have a timeline for that release?

**Comment by denysoblohin-okta** [comment]
@mraible The fix is included in 6.6.1 release

**Comment by mraible** [comment]
@denysoblohin-okta I can confirm this fixes the problem and I'm able to compile my app. I'll open a new issue for the warnings I see now.
