### ISSUE TITLE
after updating to v7.0.0 authClient.start() does not exist 

### ISSUE THREAD

**Issue by harpreetmand** [okta/okta-signin-widget#2907]
### Describe the bug

after updating okta widget to v7.0.0 singing in though social iDp using new window flow is broken.
We used `oktaSignIn.authClient.start()` to do cross window synchronization. after the update `oktaSignIn.authClient.start()` does not exist.
If i remove `oktaSignIn.authClient.start()`:
New window approach:
 clicking on social iDp open the new window, after singing in the window closes but my original pages does not auto refresh. If I manually refresh the page then i'm signed in.

redirect approach(same page):
works as intended.

### What is expected to happen?

to be able to sign in new window using okta widget

### What is the actual behavior?

get an error in console `Uncaught (in promise) TypeError: oktaSignIn.authClient.start is not a function`

### Reproduction Steps

try signing in using new window and starting `oktaSignIn.authClient.start()` 

### SDK Versions

@okta/okta-signin-widget 7.0.0 (using CDN)
"@okta/okta-auth-js": "~7.0.0"

### Execution Environment

chrome

**Comment by aarongranick-okta** [comment]
@harpreetmand The authClient included by default in the widget is a subset of AuthJS and is used only used for authentication and does not include other parts of AuthJS which manage your tokens after authentication such as cross-tab synchronization. If you'd like to use the full version of AuthJS, you should add it as a dependency to your project and instantiate it separately from the widget.  As @denysoblohin-okta [showed here](https://github.com/okta/okta-signin-widget/issues/2907#issuecomment-1307359811) you can optionally pass an instance of AuthJS to the widget. However as long as the two AuthJS instances are of the same version and are configured the same they should have no problem working together.

**Comment by aarongranick-okta** [comment]
If you are using this method to clear transaction storage before rendering the widget, instead use a unique `state` value on each request. The widget will automatically clear any transaction storage that does not match the current state.
